language: go

go:
  - 1.8
  - 1.9

cache:
  - vendor

before_install:
  # install dep
  - curl -L https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 > $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go test -v -race ./...
